services:
  app:
    container_name: tool-in-docker
    # build:
    #   context: build_local
    #   args:
    #     username: user
    #     uid: 1000
    #     gid: 1000
    #     homedir: /mnt/c/Users
    image: peccu/tool-in-docker:emacs-x
    environment:
      - TOOLTYPE=tool
      # X11
      - DISPLAY
      # Wayland
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      # PulseAudio
      - PULSE_SERVER
      # Docker in Docker : this is default sock
      # but colima overrides it so this env var is needed
      # - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /:/mnt/host
      # for mount local path into container
      - ~:$HOME
      - /home/user:/home/user
      # for chezmoi cd
      - /run/user/1000:/run/user/1000
      # tmux UID is defined in .env file
      - /tmp/tmux-${UID}:/tmp/tmux-${UID}
      - /clip:/clip
      - /open:/open
      # X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Wayland and PulseAudio
      - /mnt/wslg:/mnt/wslg
      # vGPU
      - /dev/dxg:/dev/dxg
      - /usr/lib/wsl:/usr/lib/wsl
      # Docker in Docker
      # test by curl --unix-socket /var/run/docker.sock http://localhost/version
      - /var/run/docker.sock:/var/run/docker.sock
      # # for Colima
      # # sudo ln -sf ~/.colima/default/docker.sock /var/run/docker.sock
      # - ~/.colima/default/docker.sock:$HOME/.colima/default/docker.sock
    ports:
      - 8080:8080
    # working_dir: /root
    # entrypoint: tail -f /dev/null
    # entrypoint: sleep infinity
    # stop_signal: SIGKILL
    restart: always
    # networks:
    #   - gitea
    #   - default
  cron:
    profiles: ["cron"]
    build: build_cron
    restart: always
    volumes:
      - ~:/root
      # - ./crontask/cron.daily:/etc/cron.daily:ro
      # - ./crontask/cron.hourly:/etc/cron.hourly:ro
      - ./crontask/cron.monthly:/etc/cron.monthly:ro
      # - ./crontask/cron.weekly:/etc/cron.weekly:ro
    # working_dir: /root
    # entrypoint: tail -f /dev/null
    # command: crond -f -l 8
    stop_signal: SIGKILL
  tunnel:
    profiles:
      - tunnel
    container_name: tool-in-docker_tunnel
    build:
      context: build_tunnel
      args:
        username: user
        uid: 1000
        gid: 1000
        homedir: /mnt/c/Users
    environment:
      # local pc -- TUNNEL_LOCAL_PORT -- TUNNEL_BASTION_HOST -- TUNNEL_TARGET_HOST:TUNNEL_TARGET_PORT
      - TUNNEL_LOCAL_PORT=9999
      - TUNNEL_TARGET_HOST=internal-host
      - TUNNEL_TARGET_PORT=8080
      - TUNNEL_BASTION_HOST=bastion-host
    volumes:
      # for mount local path into container
      - ~:$HOME
    ports:
      - 9999:9999
    restart: always
    networks:
      - default

# networks:
#   gitea:
#     external: true
#     name: gitea
